worlds["sierra"] = "/home/katana/.minecraft/saves/sierra/"

renders["normalrender"] = {
    "world": "sierra",
    "title": "sierra overworld render",
    "rendermode": smooth_lighting,
    "dimension": "overworld",
}
renders["normalrender"] = {
    "world": "sierra",
    "title": "sierra overworld render",
    "rendermode": smooth_night,
    "dimension": "overworld",
}
renders["caverender"] = {
	"world": "sierra",
	"title": "sierra cave render",
	"rendermode": cave,
	"dimension": "overworld",
}

outputdir = "/home/katana/minecraftmap/"

def playerIcons(poi):
    if poi['id'] == 'Player':
        poi['icon'] = "http://overviewer.org/avatar/%s" % poi['EntityId']
        return "Last known location for %s" % poi['EntityId']

def signFilter(poi):
    if poi['id'] == 'Sign':
        return "\n".join([poi['Text1'], poi['Text2'], poi['Text3'], poi['Text4']])
