[General]
AllowGrabBaseKeypad=true
AllowGrabBaseSpecial=false
AllowGrabLocks=false
AllowGrabMiscKeypad=true
AllowGrabMiscSpecial=true
MultipleActionsBehaviour=first

[Alt%2B1.1]
Comment=Switch to desktop 1 (Desktop 1)
Enabled=true
path=/panel/desktopswitch/desktop_1

[Alt%2B2.2]
Comment=Switch to desktop 2 (desktop 2)
Enabled=true
path=/panel/desktopswitch/desktop_2

[Alt%2B3.3]
Comment=Switch to desktop 3 (desktop 3)
Enabled=true
path=/panel/desktopswitch/desktop_3

[Alt%2B4.4]
Comment=Switch to desktop 4 (desktop 4)
Enabled=true
path=/panel/desktopswitch/desktop_4

[Alt%2BD.5]
Comment=Show/hide runner dialog
Enabled=true
path=/runner/show_hide_dialog

[Alt%2BF1.6]
Comment=Show/hide main menu
Enabled=true
path=/panel/mainmenu/show_hide

[Alt%2BReturn.7]
Comment=terminator
Enabled=true
Exec=/usr/bin/terminator
