[General]
__userfile__=true

[desktopswitch]
alignment=Left
type=desktopswitch

[mainmenu]
alignment=Left
type=mainmenu

[mount]
alignment=Right
type=mount

[panel1]
alignment=-1
background-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
background-image=
desktop=0
font-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
iconSize=26
lineCount=1
opacity=-1
panelSize=40
plugins=mainmenu, desktopswitch, taskbar, tray, mount
position=Left
width=100
width-percent=true

[taskbar]
alignment=Left
autoRotate=true
buttonStyle=Icon
buttonWidth=400
closeOnMiddleClick=true
showOnlyCurrentDesktopTasks=true
type=taskbar

[tray]
alignment=Right
type=tray
